name: DB2 demo database container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'databases/db2/**'
      - '!**.adoc'
jobs:
  db2-sample-db-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/db2-demo-db
      tagname: $GITHUB_REF_NAME
      dockerfile: databases/db2/Dockerfile
      directory: databases/db2
    secrets: inherit
