name: Demo data generator container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'data-generator/**'
      - '!**.adoc'
      - '!**.container'
jobs:
  db2-sample-db-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/demo-data-generator
      tagname: $GITHUB_REF_NAME
      dockerfile: data-generator/Dockerfile
      directory: data-generator
    secrets: inherit
