name: Oracle demo database container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'databases/oracle/**'
      - '!**.adoc'
jobs:
  db2-sample-db-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/oracle-demo-db
      tagname: $GITHUB_REF_NAME
      dockerfile: databases/oracle/Dockerfile
      directory: databases/oracle
    secrets: inherit
