name: Postgresql demo database container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'databases/postgresql/**'
      - '!**.adoc'
jobs:
  db2-sample-db-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/postgresql-demo-db
      tagname: $GITHUB_REF_NAME
      dockerfile: databases/postgresql/Dockerfile
      directory: databases/postgresql
    secrets: inherit
