name: MS SQL Server demo database container build and push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'databases/sqlserver/**'
      - '!**.adoc'
jobs:
  db2-sample-db-container-build-and-push:
    uses: ./.github/workflows/reusable-container-build-and-push.yaml
    with:
      imagename: kazhar/sqlserver-demo-db
      tagname: $GITHUB_REF_NAME
      dockerfile: databases/sqlserver/Dockerfile
      directory: databases/sqlserver
    secrets: inherit
